[tool.poetry]
name = "papers"
version = "0.1.0"
description = ""
authors = ["Ernest DONG <dongcy2000@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.10,<3.11"
pandas = "^1.4.2"
statsmodels = "^0.13.2"
arch = "^5.2.0"
seaborn = "^0.11.2"

[tool.poetry.dev-dependencies]
ipykernel = "^6.13.1"
debugpy = "^1.6.0"
openpyxl = "^3.0.10"
notebook = "^6.4.12"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[[tool.poetry.source]]
name = "tuna"
url = "https://pypi.tuna.tsinghua.edu.cn/simple/"
