[tool.poetry]
name = "src"
version = "0.1.0"
description = ""
readme = "readme.md"
authors = ["Ernest DONG <dongcy2000@outlook.com>"]

[tool.poetry.dependencies]
python = "^3.9"
pandas = "^1.4.1"
seaborn = "^0.11.2"
openpyxl = "^3.0.9"
scipy = "^1.6.1"

[tool.poetry.dev-dependencies]
ipykernel = "^6.9.2"
[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
