[tool.poetry]
name = "src"
version = "0.1.0"
description = ""
readme = "readme.md"
authors = ["Ernest DONG <dongcy2000@outlook.com>"]

[tool.poetry.dependencies]
python = ">=3.10,<3.11"
pandas = "^1.4.1"
seaborn = "^0.11.2"
openpyxl = "^3.0.9"
scipy = "^1.8.0"
QuantLib = "^1.25"

[tool.poetry.dev-dependencies]
ipykernel = "^6.9.2"
pytest = "^7.1.1"
debugpy = "^1.6.0"
Pygments = "^2.12.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pyright]
extraPath = ["./.venv/lib"]
useLibraryCodeForTypes = true
[tool.black]
line-length = 88
[tool.isort]
profile = "black"
