[tool.poetry]
name = "papers"
version = "0.1.0"
description = ""
authors = ["Ernest DONG <dongcy2000@outlook.com>"]

[tool.poetry.dependencies]
python = ">=3.10,<3.11"
pandas = "^1.4.2"
openpyxl = "^3.0.10"
scipy = "^1.8.1"
seaborn = "^0.11.2"
arch = "^5.2.0"

[tool.poetry.dev-dependencies]
ipykernel = "^6.13.0"
debugpy = "^1.6.0"
notebook = "^6.4.11"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
