#+TITLE: 国际贸易第一次作业
#+DATE: <2022-03-07>
#+AUTHOR: 董晨阳 1800015446
#+EMAIL: dongcy2000@outlook.com

* Table of Contents :TOC_3:noexport:
- [[#第一题][第一题]]
- [[#第二题][第二题]]
- [[#第三题][第三题]]
  - [[#芯片][芯片]]
  - [[#高铁][高铁]]

* 第一题
#+begin_comment
“Chinese workers earn only $0.50 an hour; if we (U.S.A.) allow China to export as much as it likes, our workers will be forced down to same level. You can’t import a $10 shirt without importing the $0.50 wage that goes with it.”Discuss.（1.5分）
#+end_comment
这种说法是错误的。

中国人口较多，因而在需要大量工人的劳动密集型的工作上具有比较优势，如制造业；美国资本实力更雄厚，因而在需要重资本的工作上比较发达，如其基于石油的农业和芯片设计行业。根据李嘉图的比较优势理论，一国（地区）生产某产品的相对生产成本/机会成本比较低，则具有价格和成本上的比较优势；应生产和出口有比较优势的商品，进口没有比较优势的商品。

因此引入中国的进口不会降低美国工人整体的薪酬水平，只会降低部分从事于劳动密集型缺乏竞争力工人的薪酬水平，而从事其他资本密集型工人的工资水平因出口增加收入增高。总体而言引入自由贸易会增加产出和收入的同时降低其他成本，实际收入水平提升。
* 第二题
#+begin_comment
“The world’s poorest countries cannot find anything to export. There is no resource that is abundant—certainly not capital or land, and in small poor nations not even labor is abundant.”Discuss.（1.5分）
#+end_comment
这种说法是错误的。一个国家可能在各个方面都缺乏绝对优势，但即便一国在两种商品生产上较之另一国均处于绝对劣势，只要处于劣势的国家在两种商品生产上劣势的程度不同，处于优势的国家在两种商品生产上优势的程度不同，则处于劣势的国家在劣势较轻的商品生产方面具有比较优势，处于优势的国家则在优势较大的商品生产方面具有比较优势。
* 第三题
#+begin_comment
Give two examples of products that are traded on international markets for which there are dynamic increasing returns. In each of your examples, show how innovation and learning-by-doing are important to the dynamic increasing returns in the industry.（2分）
#+end_comment
** 芯片
芯片主流生产模式之一为 fabless + foundry 模式全球化分工，其中上游的芯片设计集中在美国，中游的芯片制造集中在台湾地区和韩国，封装测试集中在台湾地区和大陆。各个地方通过干中学（如先进封装）和技术创新（如 FinFET 工艺），得到更为先进和更加便宜的集成电路设备，维持摩尔定律。
** 高铁
2004年之前，中国还无法自主制造安全可靠的高速列车，订单需求要对外招标。随后通过以引进日本、德国、法国、加拿大等国的高铁制造技术，通过干中学融合改进创新，形成了世界先进的、走出去的、价格更低的高铁技术
